name: KMCSpaceFS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  windows-build:
  
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v4
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: "x64"
    - name: Symlink
      run: |
        mkdir "C:\Users\Anthony Kerr\source\repos\PoeticDeath"
        cd "C:\Users\Anthony Kerr\source\repos\PoeticDeath"
        New-Item -ItemType SymbolicLink -Path KMCSpaceFS -Target "D:\a\KMCSpaceFS\KMCSpaceFS"
    - name: Build Driver
      run: msbuild KMCSpaceFS.sln /p:Configuration="Release" /p:Platform=x64
    - name: Upload driver artifacts
      uses: actions/upload-artifact@v4
      with:
        name: KMCSpaceFS-Release-x64
        path: |
          x64\Release\KMCSpaceFS.sys
          src\KMCSpaceFS.inf
          src\KMCSpaceFS-VOL.inf
